config/routes.rb
Rails.application.routes.draw do

  post '/payments/add_bank_account' => 'payments#add_bank_account', :as => :add_bank_account
  post '/payments/add_credit_card' => 'payments#add_credit_card', :as => :add_credit_card
  get 'initiate_payment' => 'payments#initiate_payment', :as => :initiate_payment

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  require 'balanced'

  
  ##initiate payment
  def initiate_payment
  end


  #process the Bank Account transaction
  def add_bank_account

    get_balanced_key

    account_uri = params[:account_uri]
    company_name = "Mindfire Solutions"

    ##You can set your customer business / company name here 
    customer = Balanced::Customer.new({name: company_name}).save
    customer_uri = customer.href
    get_customer = Balanced::Customer.fetch(customer_uri)
   
    bank_account = Balanced::BankAccount.fetch(account_uri)
    bank_account.associate_to_customer(customer_uri)
    
    ##befor debiting your customer you need to verify their bank account as per balanced payment
    bank_account = Balanced::BankAccount.fetch(account_uri)
    verify_bank_account = bank_account.verify
    verification = Balanced::BankAccountVerification.fetch(verify_bank_account.href)
    verification.confirm(
      amount_1 = 1,
      amount_2 = 1
    )
    
    amount_in_dollars = params[:amount].to_i
    #amount_in_dollars * 100 convert into cents
    debit = bank_account.debit(:amount => amount_in_dollars * 100, appears_on_statement_as: "Debit Amount")
    
    ##You can save the response in your db for future use
    #debit.transaction_number
    #debit.amount
    #debit.statusdebit.created_at
    
    #get your balanced marketplace
    marketplace = Balanced::Marketplace.my_marketplace
    
    credit = get_marketplace_bank_account.credit(:amount => debit.amount, appears_on_statement_as: "Credit Amount")

    
    return render json: {success: ["Debit Transaction:: #{debit.attributes}", "Credit Transaction:: #{credit.attributes}"] }

  end
  

  #process the credit card transaction
  def add_credit_card

    get_balanced_key
    card_uri = params[:card_uri]

    company_name = "Mindfire Solutions"
    customer = Balanced::Customer.new({name: company_name}).save
    customer_uri = customer.href
    get_customer = Balanced::Customer.fetch(customer_uri)
    card = Balanced::Card.fetch(card_uri)
    card.associate_to_customer(customer_uri)
   

    amount_in_dollars = params[:amount].to_i
    #amount_in_dollars * 100 convert into cents

    debit = card.debit(:amount => amount_in_dollars * 100, appears_on_statement_as: "Debit Amount")
    
    ##You can save the response in your db for future use
    #debit.transaction_number
    #debit.amount
    #debit.statusdebit.created_at
  
    #get the balanced market place
    marketplace = Balanced::Marketplace.my_marketplace
    
    credit = get_marketplace_bank_account.credit(:amount => debit.amount, appears_on_statement_as: "Credit Amount")


    return render json: {success: ["Debit Transaction:: #{debit.attributes}", "Credit Transaction:: #{credit.attributes}"] }

  end


  private
  
  ##here is the demo bank account uri on which you need to credit the amount
  def get_marketplace_bank_account
    Balanced::BankAccount.find("/v1/bank_accounts/BAj6sNNBdMp5WmY6PJ7sAu3")
  end
  
  ##get the balanced marketplace key
  def get_balanced_key
    config = YAML.load_file("#{Rails.root.to_s}/config/balanced.yml")[Rails.env]
    Balanced.configure(config['BALANCED_KEY'])

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= link_to "See Demo", initiate_payment_path, data: { no_turbolink: true } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo Balanced Payment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= link_to( (image_tag "balanced_logo.png") , "http://www.balancedpayments.com", target: "_blank") %>

<%= yield %>

</body>
</html>

app/views/payments/_bank_account_form.html.erb
<%= form_tag("", id: "bank-account-form") do %>

    <div >
      <label ></label>
      <div>
        <%= text_field_tag "ba-name", "Test Account", :placeholder => "Account Holder's Name", :class => "ba-name", :autocomplete => "off" %>
        
      </div>
    </div>
    <div >
      <label ></label>
      <div>
      	<%= text_field_tag "ba-rn", "321174851", :placeholder => "Routing Number", :class => "ba-rn", :maxlength => 9, :autocomplete => "off" %>
        <span class="help-block">Enter your 9 digit routing number</span>
      </div>
    </div>

    <div >
      <label ></label>
      <div>
        <%= text_field_tag "ba-an", "9900000003", :placeholder => "Account Number", :class => "ba-an", :maxlength => 12, :autocomplete => "off" %>
         <span class="help-block">Enter your bank account number<span>
      </div>
    </div>

    <div >
      <label ></label>
      <div>
        <%= select_tag "ba-type", "<option value=''>Select Account Type</option><option value=\"checking\">CHECKING</option><option value=\"savings\">SAVINGS</option>".html_safe %>
        <span class="help-block">Specify your account type</span>
      </div>
    </div>

    <div >
      <label ></label>
      <div>
        <%= submit_tag "Pay", class: "btn", id: "ba-submit", disabled_with: "paying..." %>
      </div>
    </div>

<% end %>

app/views/payments/_credit_card_form.html.erb
<%= form_tag("", id: "credit-card-form") do %>
  
    <div >
      <label ></label>
      <div>
        <%= text_field_tag "cc-name", "Test", :placeholder => "Enter Name on Card", :autocomplete => "off" %>
      </div>
    </div>
    <div >
      <label ></label>
      <div>
        <%= text_field_tag "cc-number", "4111111111111111", :placeholder => "Enter Credit Card Number", :maxlength => 16, :autocomplete => "off" %>
      </div>
    </div>
    <div >
      <label ></label>
      <div>
      	<%= text_field_tag "cc-em", "12", :placeholder => "Month",  :class => "cc-em", :maxlength => 2, :autocomplete => "off"%>
        <%= text_field_tag "cc-ey", "2014", :placeholder => "Year", :class => "cc-ey", :maxlength => 4, :autocomplete => "off"%>
      </div>
    </div>
    <div >
    <label ></label>
      <div>
        <%= select_tag "cc-type", "<option value=''>Select Card Type</option><option value=\"VISA\">VISA</option><option value=\"Mastercard\">Mastercard</option><option value=\"American Express\">American Express</option><option value=\"Discover\">Discover</option>".html_safe %>
      </div>
    </div>

    <div  id ="zip_code_required" style= "display:none;">
    <label ></label>
      <div>
        <%= text_field_tag "cc-zip-code", "12345", :placeholder => "Zip Code", :class => "cc-zip-code", :maxlength => 5, :autocomplete => "off" %></br>
        <span class="help-block">Credit card's billing postal code</span>
      </div>
    </div>

    <div >
      <label ></label>
      <div>
        <%= text_field_tag "cc-csc", "123", :placeholder => "Security Code", :maxlength => 4, :class => "cc-csc", :autocomplete => "off" %>
      </div>
    </div>
    <div >
      <label ></label>
      <div>
        <%= submit_tag "Pay", class: "btn", id: "cc-submit", disabled_with: "paying..." %>
      </div>
    </div>

<% end %>

app/views/payments/initiate_payment.html.erb
<% config = YAML.load_file("#{Rails.root.to_s}/config/balanced.yml")[Rails.env] %>
<script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>
<script >
  balanced.init('/v1/marketplaces/<%= config['BALANCED_MARKETPLACE'] %>');
</script>

 </br>
<%= link_to "Back", root_path, data: { no_turbolink: true } %>
 </br></br>

 <div>
  <label >Payment Amount</label>
  <div >
    $<%= text_field_tag "amount", 100.00 %>
  </div>
</div>

<div>
  <label >Payment Options</label>
  <div >
    <%= radio_button_tag "bank_account", 1, false, :class => "jqTransformRadio", name: "payment_option" %>
      Bank Account &nbsp;&nbsp;
    <%= radio_button_tag "credit_card", 0, false,  :class => "jqTransformRadio", name: "payment_option" %>
     Credit Card
  </div>
</div>

<div id ="credit_card_info" style="display:none;">
  <%= render partial: "payments/credit_card_form" %>
</div>

<div id ="bank_account_info" style="display:none;">
  <%= render partial: "payments/bank_account_form" %>
</div>
</br></br>

<div id= "processing" style= "display:none;">
  <strong>Please do not refresh or press back button</strong>
  Your transaction is Processing...
</div>

<div id= "debit_response"></div> 
</br>
</br>
<div id= "credit_response"></div> 